
# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "file:///workspaces/typescript-node/Downloads/test-ecs-ado/amazon-ecs-for-azure-devops-hosted-agents/"
}

include "root" {
  path = find_in_parent_folders("root.hcl")
}

locals {
  common_vars  = yamldecode(file("./common_vars.yaml"))
  aws_env      = get_env("AWS_ENV", "sandbox")
  region       = get_env("AWS_REGION", "us-east-1")
  project_name = "ado-ecs-runner"
  environment  = local.common_vars.tags.Environment
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------
  provider_region    = local.region
  project_name       = local.project_name
  environment        = local.environment
  source_repo_name   = "ado-ecs-repo"
  source_repo_branch = "main"
  create_new_repo    = true
  create_new_role    = true
  source_repo_name   = "ado-ecs-repo"
  source_repo_branch = "main"
  create_new_repo    = true
  create_new_role    = true
  stage_input = [
    { name = "build-image", category = "Test", owner = "AWS", provider = "CodeBuild", input_artifacts = "SourceOutput", output_artifacts = "ValidateOutput-terraform" }
  ]
  container_env_vars = [
    { name = "LOG_LEVEL", value = "DEBUG" },
    { name = "PORT", value = "80" },
    { name = "AZP_URL", value = "https://devops.magaya.com/tfs/DevelopmentCollection/" }, // Replace with your ADO Org URL
    { name = "AZP_POOL", value = "MagayaAnsibleConfiguration" },                          // Replace with your ADO Agent Pool name
  ]
  container_port         = 80
  container_host_port    = 80
  ecs_service_count      = "2"
  container_image_tag    = "ado-ecs"
  ecr_repo_name          = "ado-ecs-ecr"
  ecs_cluster_name       = "ado-ecs"
  ecs_container_def_name = "ado-ecs-tf"
  ecs_service_name       = "ado-ecs-svc"
  ecs_ado_patsecret_name = "ecs-ado-pat-secret"

  lambda_memory_size = "128"
  lambda_timeout     = "90"

  subnet_ids      = "subnet-0249659dfd8507374"
  security_groups = "sg-02ec4eb7482cfef0a"
  ado_org         = "8995e0b5-d004-439f-8353-fbdbf8a199df"

  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

}
